### ISSUE TITLE
on_message插件运行错误，并且无法添加至白名单

### ISSUE THREAD

**Issue by kexue-z** [HibiKier/nonebot_plugin_statistical#1]
。。。一时半会可能说不清

某个插件使用了`on_message`
例如`bilibili`插件
```py
parse_bilibili_json = on_message(priority=1, permission=GROUP, block=False)
```
当其他使用`on_command`插件匹配到指令时，会将cmd同时自动记录到`bilibili`插件和其他插件中
导致使用了`on_message`的插件计数过高

![CleanShot 2021-07-09 at 23 37 15](https://user-images.githubusercontent.com/71873002/125103102-9a553800-e10e-11eb-8d7b-ce92966c95f6.png)

并且无法被白名单功能不生效

![CleanShot 2021-07-09 at 23 42 56](https://user-images.githubusercontent.com/71873002/125103920-66c6dd80-e10f-11eb-974f-fd7de3bd7e64.png)

![image](https://user-images.githubusercontent.com/71873002/125103955-6f1f1880-e10f-11eb-998c-84f42abab502.png)

另外`nonebot_plugin_wordbank`却可以正常统计并且白名单生效。。
可能是我的`bilibili`插件有问题？

**Comment by HibiKier** [comment]
是统计插件的问题，钩子函数里区分不开on_message和on_command，打算在.env添加配置statistical_black_model和statistical_black_priority来屏蔽不统计一些插件

**Comment by HibiKier** [comment]
已更新
